src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[UniqueEntity('title')]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['index'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 255,
    )]
    #[Groups(['index'])]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Groups(['index'])]
    private ?string $slug = null;

    #[ORM\Column(length: 1000)]
    #[Assert\Length(
        min: 2,
        max: 1000,
    )]
    private ?string $presentation = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private ?string $content = null;

    #[ORM\Column]
    #[Groups(['index'])]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['index'])]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[Groups(['index'])]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Document::class, orphanRemoval: true)]
    private Collection $documents;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(?string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Document>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents->add($document);
            $document->setArticle($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getArticle() === $this) {
                $document->setArticle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getClass(): string
    {
        $path = explode('\\', __CLASS__);
        return array_pop($path);
    }
}

src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DocumentRepository;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: DocumentRepository::class)]
#[UniqueEntity('title')]
/**
 * @Vich\Uploadable
 */
class Document
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 255,
    )]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    /**
     * @Vich\UploadableField(mapping="document_files", fileNameProperty="filename")
     * @var File
     */
    private $documentFile;

    #[ORM\Column(length: 1000, nullable: true)]
    #[Assert\Length(
        min: 2,
        max: 1000,
        minMessage: "Ce champ doit faire au moins 2 caractères.",
        maxMessage: "Ce champ ne peut pas faire plus de 1000 caractères."
    )]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'documents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
    
    public function getDocumentFile(): ?File
    {
        return $this->documentFile;
    }
    
    public function setDocumentFile(?File $documentFile): self
    {
        $this->documentFile = $documentFile;

        if ($documentFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }

    public function getFileInfo()
    {
        return pathinfo($this->filename);
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getClass(): string
    {
        $path = explode('\\', __CLASS__);
        return array_pop($path);
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre*'
            ])
            ->add('presentation', TextareaType::class, [
                'label' => 'Courte présentation*',
                'help' => 'Ecrivez une courte présentation de moins de 1000 caractères'
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Corps de l\'article*',
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('c')->orderBy('c.position', 'ASC');
                },
                'choice_label' => function (?Category $category) {
                    if (!$category) {
                        return '';
                    }

                    $title = $category->getTitle();

                    if ($category->getParent() === null) {
                        return $title;
                    }
                    
                    return '-- ' . $title;
                },
                'label' => 'Catégorie*',
                'attr' => [
                    'data-choices' => 'choices',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Settings;
use App\Repository\ArticleRepository;
use App\Repository\SettingsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{

    #[Route('/article', name: 'app_article_index')]
    public function index(ArticleRepository $articleRepository, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);

        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findPaginated($page),
            'is_article' => true,
        ]);
    }

    #[Route('/category/{slug}', name: 'app_category_show')]
    public function section(Category $category, ArticleRepository $articleRepository, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);

        return $this->render('article/category.html.twig', [
            'category' => $category,
            'articles' => $articleRepository->findPaginated($page, 14, $category->getId()),
            'is_category' => true,
        ]);
    }

    #[Route('/article/{slug}', name: 'app_article_show')]
    public function article(Article $article): Response
    {
        return $this->render('article/article.html.twig', [
            'article' => $article,
            'is_article' => true,
        ]);
    }
}

templates/article/_article_card.html.twig
<article class="item border bg-light flex-fill position-relative">
    <div class="item__body">
        <p class="item__description">
            <i class="fas fa-fw fa-tag"></i>
            <span class="fst-italic">
                {{ article.category ? article.category.title : "Aucune catégorie"  }}
            </span>
        </p>
        <h3 class="item__title">
            <a href="{{ path('app_article_show', {'slug': article.slug}) }}" class="text-decoration-none text-reset stretched-link">
                {{ article.title }}
            </a>
        </h3>
        <p class="item__description mt-2 mb-3">{{ article.presentation }}</p>
    </div>
</article>

templates/article/_category_list.html.twig
<div class="row mt-3">
	{% for category in categories %}
        <div class="col-md-6 col-lg-4 d-flex">
            <article class="item border bg-light flex-fill">
                <div class="item__body">
                    <h3 class="item__title">
                        <a href="{{ path('app_category_show', {'slug': category.slug}) }}" class="text-decoration-none text-reset">
                            {{ category.title }} <i class="fas fa-fw fa-external-link-alt"></i>
                        </a>
                    </h3>
                    <p class="item__description mt-2 mb-3">{{ category.description }}</p>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdown{{category.id}}" data-bs-toggle="dropdown" aria-expanded="false">
                            Sections
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown{{category.id}}">
                            {% for subCategory in category.subCategories %}
                                <li><a class="dropdown-item" href="{{ path('app_category_show', {'slug': subCategory.slug}) }}">{{ subCategory.title }}</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="#" class="text-muted">Aucune sous catégorie</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </article>
        </div>
    {% endfor %}
</div>

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }} | {{ parent() }}{% endblock %}

{% block header %}
	{% if app_banner|length > 1 %}
        {% set banner_file = asset(app_banner) %}
		{% set bg_header = 'background: linear-gradient(to bottom, rgba(0, 0, 0, 0.85), rgba(54, 54, 54, 0.3)),url("'~banner_file~'") center center / cover no-repeat;' %}
	{% else %}
		{% set bg_header = 'background:rgb(90 90 90)' %}
	{% endif %}
	<header class="header" style="{{bg_header}}">
		<div class="container">
			<div class="text-end">
				<p class="mb-0">
					{% if article.category %}
						<a href="{{ path('app_category_show', {'slug': article.category.slug}) }}" class="text-reset">{{ article.category.title }}</a>
					{% else %}
						Aucune catégorie
					{% endif %}
					<i class="fas fa-fw fa-tag"></i>
				</p>
				<h1 class="display-3 mt-0">{{ article.title }}</h1>
				<p class="fs-5 fst-italic">{{ language_name }}</p>
			</div>
		</div>
	</header>
{% endblock %}

{% block body %}
        <div class="text-end mb-3 fs-5 icons-bar">
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('app_admin_article_edit', {id: article.id}) }}" class="text-decoration-none" title="éditer">
                    <i class="fas fa-edit fa-fw"></i>
                </a>
                <a href="{{ path('app_document_admin_new', {id: article.id}) }}" class="text-decoration-none" title="Ajouter un document">
                    <i class="fas fa-file-upload fa-fw"></i>
                </a>
            {% endif %}
            <a href="javascript:print()" class="text-decoration-none" title="Imprimer">
                <i class="fas fa-print fa-fw"></i>
            </a>
        </div>
	<div class="lead text-center mb-4">{{ article.presentation }}</div>
	<ul class="nav nav-tabs" id="myTab" role="tablist">
		<li class="nav-item" role="presentation">
			<button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">
                Article
            </button>
		</li>
		<li class="nav-item" role="presentation">
			<button class="nav-link" id="document-tab" data-bs-toggle="tab" data-bs-target="#document" type="button" role="tab" aria-controls="document" aria-selected="false">
                Documents
            </button>
		</li>
	</ul>
	<div class="tab-content p-2" id="myTabContent">
		<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            {{ article.content|raw }}
        </div>
		<div class="tab-pane fade" id="document" role="tabpanel" aria-labelledby="document-tab">
            <div class="row">
                {% for document in article.documents %}
                    {% set path_file = vich_uploader_asset(document) %}
                    <div class="col-md-3">
                        <div class="card bg-white p-0">
                            <div class="card-header">
                                <h3 class="card-title h5 mb-0">
                                    <a href="{{ path_file }}" download>
                                        {{ document.title }}
                                    </a>
                                </h3>
                            </div>
                            {% if document.fileInfo.extension in ['jpeg', 'jpg', 'gif', 'png'] %}
                                <a href="{{ path_file }}">
                                    <img src="{{ path_file }}" alt="{{ document.title }}" class="card-img-top">
                                </a>
                            {% endif %}
                            <div class="card-body">
                                <div class="card-text">{{ document.description  ? document.description : 'Aucune description' }}</div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p class="text-center text-muted">Aucun document</p>
                {% endfor %}
            </div>
        </div>
	</div>
{% endblock %}

templates/article/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.title }} | {{ parent() }}{% endblock %}

{% block header %}
	{% if app_banner|length > 1 %}
        {% set banner_file = asset(app_banner) %}
        {% set bg_header = 'background: linear-gradient(to bottom, rgba(0, 0, 0, 0.85), rgba(54, 54, 54, 0.3)),url("'~banner_file~'") center center / cover no-repeat;' %}
    {% else %}
        {% set bg_header = 'background:rgb(90 90 90)' %}
    {% endif %}
	<header class="header" style="{{bg_header}}">
		<div class="container">
			<div class="text-end">
				<p class="mb-0 text-decoration-underline">
                    {% if category.parent %}
						<a href="{{ path('app_category_show', {'slug': category.parent.slug}) }}" class="text-reset">{{ category.parent.title }}</a>
					{% else %}
						Aucun parent
					{% endif %}
					<i class="fas fa-fw fa-tag"></i>
                </p>
				<h1 class="display-3 mt-0">{{ category.title }}</h1>
				<p class="fs-5 fst-italic">{{ language_name }}</p>
			</div>
		</div>
	</header>
{% endblock %}

{% block body %}
    <div class="text-end mb-3 fs-5 icons-bar">
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('app_admin_category_edit', {id: category.id}) }}" class="text-decoration-none" title="éditer">
                <i class="fas fa-edit fa-fw"></i>
            </a>
            <a href="{{ path('app_admin_article_new', {'category': category.id}) }}" class="text-decoration-none" title="ajouter un article">
                <i class="fas fa-plus-circle fa-fw"></i>
            </a>
        {% endif %}
        <a href="javascript:print()" class="text-decoration-none" title="Imprimer">
            <i class="fas fa-print fa-fw"></i>
        </a>
    </div>
    
	<div class="row my-3">
        <div class="col-md-9">
            <h2>Articles de cette catégorie</h2>
            <p class="text-muted">
                <strong>{{ articles|length }}</strong> article{{ articles.getTotalItemCount > 1 ? 's' : '' }} 
                sur <strong>{{ articles.getTotalItemCount }}</strong>.
            </p>
            <div class="row">
                {% for article in articles %}
                    <div class="col-md-6 d-flex">
                        {% include "article/_article_card.html.twig" %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3 border-start">
            <aside>
                <h3 class="h5">Sous catégories</h3>
                {% if category.subCategories is not empty %}
                    <ul>
                        {% for subCategory in category.subCategories|sort((a, b) => a.position <=> b.position) %}
                            <li>
                                <a href="{{ path('app_category_show', {'slug': subCategory.slug}) }}">
                                    {{ subCategory.title }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="fst-italic">Aucune</p>
                {% endif %}
            </aside>
        </div>
    </div>
    {{ knp_pagination_render(articles, null, {}, {'align': 'center'}) }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles | {{ parent() }}{% endblock %}

{% block header %}
	{% if app_banner|length > 1 %}
        {% set banner_file = asset(app_banner) %}
        {% set bg_header = 'background: linear-gradient(to bottom, rgba(0, 0, 0, 0.85), rgba(54, 54, 54, 0.3)),url("'~banner_file~'") center center / cover no-repeat;' %}
    {% else %}
        {% set bg_header = 'background:rgb(90 90 90)' %}
    {% endif %}
	<header class="header" style="{{bg_header}}">
		<div class="container">
			<div class="text-end">
				<p class="mb-0 text-decoration-underline">Articles</p>
				<h1 class="display-3 mt-0">{{ language_name }}</h1>
				<p class="fs-5 fst-italic">{{ original_language_name }}</p>
			</div>
		</div>
	</header>
{% endblock %}

{% block body %}
    <h2>Index des articles</h2>
    <p class="text-muted">
        <strong>{{ articles|length }}</strong> article{{ articles.getTotalItemCount > 1 ? 's' : '' }} 
        sur <strong>{{ articles.getTotalItemCount }}</strong>.
    </p>
	<div class="row my-3">
        {% for article in articles %}
            <div class="col-md-6 col-lg-4 d-flex">
                {% include "article/_article_card.html.twig" %}
            </div>
        {% endfor %}
    </div>
    {{ knp_pagination_render(articles, null, {}, {'align': 'center'}) }}
{% endblock %}